apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
  WHATSAPP_FROM: {{ .Values.secrets.whatsappFrom | quote }}
  WHATSAPP_TO: {{ .Values.secrets.whatsappTo | quote }}